diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    publish_rate: 50.0
    base_frame_id: base_footprint
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]
    wheel_separation: 0.12
    wheel_radius: 0.09
    use_stamped_vel: false
    cmd_vel_timeout: 0.2

    # Velocity limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 10.0       # adjust to your desired max linear speed
        min_velocity: -10.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0       # adjust to your desired max angular speed
        min_velocity: -2.0
