diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    publish_rate: 50.0
    base_frame_id: base_footprint
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]
    wheel_separation: 0.12
    wheel_radius: 0.09
    use_stamped_vel: false
    cmd_vel_timeout: 0.2